### ISSUE TITLE
Missing multipleOr tests for status parameter tests

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#61] opened 2024-04-21 22:05 UTC
AU Core mandates support for multipleOr for the status search parameter. Need to add to:
* 1.19.04 Optional Server returns valid results for Procedure search by status
* 1.19.07 Optional Server returns valid results for Procedure search by patient + status
* 1.17.07 Optional Server returns valid results for MedicationRequest search by status
* 1.17.09 Server returns valid results for MedicationRequest search by patient + intent + status
* 1.11.05 Optional Server returns valid results for Observation search by status (and equivalent in other Observation profiles)
* 1.11.09 Server returns valid results for Observation search by patient + category + status (and equivalent in other Observation profiles)

**Comment by projkov** [comment] 2024-04-27 07:36
Hello @dt-r 

I can do this manually; it's not a problem. But I have a question: where can I find information about 'multipleOr' in the Implementation Guide files?

I want to understand why the generator is missing 'multipleOr.' I'm trying to find information about 'multipleOr' in the IG 0.3.0-ballot, and I can only find '_multipleOr' in SearchParameter-au-core-clinical-patient.json and SearchParameter-au-core-practitionerrole-practitioner.json.

**Comment by dt-r** [comment] 2024-04-28 21:57
multipleOr is defined on each Profile page. That should also be in the documentation element of CapabilityStatements.

As with chained elements, the way to programmatically declare support for multipleOr is to profile a SearchParameter, and then when a search parameter is referenced in the CapabilityStatement to point to the AU Core SearchParameter instead of the FHIR definition. CapabilityStatements do not have inline entries for things like multipleOr, chained elements, modifiers, or comparators.

**Comment by projkov** [comment] 2024-04-29 10:46
Hello @dt-r 

```
multipleOr is defined on each Profile page.
```

If I understand correctly, the algorithm to determine the "multipleOr" attribute for the searchParameter should proceed as follows:

1. Check the SearchParameters profile;
2. If a profile for the SearchParameter does not exist, check the default FHIR SearchParameter.

Is it correct?

**Comment by projkov** [comment] 2024-04-29 10:57
> Hello [@dt-r](https://github.com/dt-r)
> 
> ```
> multipleOr is defined on each Profile page.
> ```
> 
> If I understand correctly, the algorithm to determine the "multipleOr" attribute for the searchParameter should proceed as follows:
> 
> 1. Check the SearchParameters profile;
> 2. If a profile for the SearchParameter does not exist, check the default FHIR SearchParameter.
> 
> Is it correct?

I'm asking about it because in the current case, for example, "Procedure.status," I can't understand where the multipleOr attribute is set to True.

1. There is no specific SearchParameter profile for "Procedure-status."
2. There is no "multipleOr" attribute for "Procedure-status" within the search parameters FHIR file at https://hl7.org/fhir/search-parameters.json.

**Comment by dt-r** [comment] 2024-04-30 04:02
AU Core adds the multipleOr requirement in narrative e.g. if present in the CapabilityStatement itself it would be in the documentation element. The way to do this structurally is for AU Core to define a search parameter. AU Core does not yet have done this - it is unlikely to do so in R1. 

> You are welcome to suggest that AU Core adds in more profiled SearchParameters to the IG via adding a JIRA change request. I don't think it will make it into R1. I am on the fence at which release of AU Core we may introduce this to. It is rare for an IG to do anything more than document in narrative the use of chained params or multipleOr etc. because almost no-one is using those artefacts. I'd be interested to see how many people would want to use them and how.

**Comment by projkov** [comment] 2024-04-30 04:17
@dt-r Hello

I got it! Thank you.

**Comment by projkov** [comment] 2024-05-05 14:18
The fix for this issue will be merged. 
Now, multipleOr and multipleAnd requests are independent tests. It's simpler to read and understand.

https://github.com/hl7au/au-fhir-core-inferno/pull/75

**Comment by projkov** [comment] 2024-06-19 08:02
Hello @dt-r 

Changes related to this ticket should be available on the server. Could you retest it?

**Comment by StephThaoOng** [comment] 2024-06-22 13:18
Moved to "on-hold" status; to be discussed at Sparked tooling meeting 24/6.
Check:

1.  for testing support for multipleOR search on a parameter when combined with other search parameters, is it acceptable to implement this test independently? Whilst perhaps not robust, I think it's adequate for the purposes of testing a system's capability to support AU Core. Separate issues to be raised as enhancements, if needed. 
2.  for _Procedure search by patient + status_ and _Observation search by patient + category + status_ which are both have a conformance expectation of SHOULD, is it acceptable for the independent multipleOR tests to have a conformance expectation of SHALL? i.e. the SHALL support for multilpleOR is conditional on whether claiming support for the SHOULD combined parameters search.

**Comment by StephThaoOng** [comment] 2024-06-24 08:20
> Moved to "on-hold" status; to be discussed at Sparked tooling meeting 24/6. Check:
> 
> 1. for testing support for multipleOR search on a parameter when combined with other search parameters, is it acceptable to implement this test independently? Whilst perhaps not robust, I think it's adequate for the purposes of testing a system's capability to support AU Core. Separate issues to be raised as enhancements, if needed.
> 2. for _Procedure search by patient + status_ and _Observation search by patient + category + status_ which are both have a conformance expectation of SHOULD, is it acceptable for the independent multipleOR tests to have a conformance expectation of SHALL? i.e. the SHALL support for multilpleOR is conditional on whether claiming support for the SHOULD combined parameters search.

1. 24/6 Infra&Tooling meeting - agreed that for AU Core capability testing, it is reasonable to implement tests for "multipleOr" search and "multipleAnd" search separately.
2. @projkov I have discussed with Michael Wilson and we think the multipleOR tests for:

     - _Procedure search by patient + status_, and 
     - _Observation search by patient + category + status_ 

    should be Optional tests. We can leave the conformance (SHALL/SHOULD) out/empty or mark it "SHOULD".

**Comment by projkov** [comment] 2024-06-24 08:37
@StephThaoOng 

I want to clarify about the second item in the list. We already have these tests as optional. I'm talking about:

1.3.09 Optional (SHOULD) Server returns valid results for Observation search by patient + category + status (as an example)
1.18.07 Optional (SHOULD) Server returns valid results for Procedure search by patient + status

Or I missing something?

**Comment by StephThaoOng** [comment] 2024-06-24 09:15
> the multipleOR tests for:
> 
> * _Procedure search by patient + status_, and
> * _Observation search by patient + category + status_
> 
> should be Optional tests. We can leave the conformance (SHALL/SHOULD) out/empty or mark it "SHOULD".

Hi @projkov sorry for the copy/paste error. The above was intended the read:
The test for multipleOR search on status in the Procedure and Observation test suites should be optional if implemented separately since the combined search is SHOULD.
What are your thoughts?

**Comment by projkov** [comment] 2024-06-24 09:21
> > the multipleOR tests for:
> > 
> > * _Procedure search by patient + status_, and
> > * _Observation search by patient + category + status_
> > 
> > should be Optional tests. We can leave the conformance (SHALL/SHOULD) out/empty or mark it "SHOULD".
> 
> Hi [@projkov](https://github.com/projkov) sorry for the copy/paste error. The above was intended to read: The test for multipleOR search on status in the Procedure and Observation test suites should be optional if implemented separately since the combined search is SHOULD. What are your thoughts?

Hello @StephThaoOng 
I guess I understand now. 
We have separate tests for "multipleOr" status search like:
1. (SHALL) Server returns valid results for Observation multipleOr search by status
2. (SHALL) Server returns valid results for Procedure multipleOr search by status

I need to make them optional and mark them as SHOULD. Am I right?

**Comment by StephThaoOng** [comment] 2024-06-24 10:21
> Hello [@StephThaoOng](https://github.com/StephThaoOng) I guess I understand now. We have separate tests for "multipleOr" status search like:
> 
> 1. (SHALL) Server returns valid results for Observation multipleOr search by status
> 2. (SHALL) Server returns valid results for Procedure multipleOr search by status
> 
> I need to make them optional and mark them as SHOULD. Am I right?

Yes make them optional tests. My preference, for example for Procedure, is:

```
title 'Server returns valid results for Procedure multipleOr search by status'
      description %(If a server supports searching by patient + status on the Procedure resource, the server SHALL support searching by multipleOr
status. This test will pass if resources are returned and match the search criteria. If
none are returned, the test is skipped.
```

But open to however you'd like to change it, as long as it's an optional test. 

I've just noted that the Inferno US Core Test Kit implements the tests for multipleOR search on _status_ on Procedure and Observation profiles within the combined search test. Despite this, I think can move forward with making them separate, optional tests for now. Thanks @projkov

**Comment by projkov** [comment] 2024-06-24 14:08
@StephThaoOng Hello Steph

Multiple OR tests for status in Procedure and Observation are optional and should have a SHOULD prefix. You can re-test it. Thanks!

**Closed** 2024-06-25 06:12 UTC
Labels: Prioroty::Medium
